### ISSUE TITLE
Trying to add support for JWT Tokens

### ISSUE THREAD

**Issue by nook24** [drosoCode/filebrowser#3]
Hi,

I'm currently trying to add support for the JWT Tokens used by the OnlyOffice Server, unfortunatly I dont know where to start.
I pulled your changes into a fork and replaced the onlyoffice configuration with a struct to be able to add more options
https://github.com/nook24/filebrowser/tree/onlyoffice

Unfortunately i have no idea who (and how) needs to generate the token. Do you have any experience with this or tips?

**Comment by drosoCode** [comment]
Hi,

I have added support for JWT in my branch.
To configure JWT, you need to have a secure connection to yourfilebrowser server (it will not work with unsecured http as we are using the WebCrypto API) and fill the "jwt secret" field in your filebrowser general settings with the secret.

The secret is autogenerated in the most recent version of onlyoffice (there is a command to show it in the container logs). You can also set the environment variable `JWT_SECRET` to specify it yourself.
